import { useNavigate } from "react-router-dom";
import { AndroidPageHeader } from "../components/AndroidBackButton";

const TermsPage = () => {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-background">
      {/* Android Material Design Header */}
      <AndroidPageHeader
        title="Terms & Conditions"
        onBack={() => navigate(-1)}
      />

      <div className="max-w-4xl mx-auto px-4 py-6 space-y-6">
        <div className="bg-white rounded-2xl p-6 shadow">
          <p className="text-xs text-gray-500 mb-6">LAST REVISION: [20/06/2025]</p>
          
          <div className="space-y-6 text-sm text-gray-700 leading-relaxed">
            <p>
              THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION TECHNOLOGY ACT, 2000 ("IT ACT") AND RULES ISSUED THEREUNDER, AS APPLICABLE AND THE PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS STATUTES AS AMENDED BY THE IT ACT AND IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF APPLICABLE LAWS, INCLUDING THE CONSUMER PROTECTION (E-COMMERCE) RULES 2020, THAT REQUIRE PUBLISHING THE RULES AND REGULATIONS, PRIVACY POLICY AND TERMS AND CONDITIONS FOR ACCESS OR USAGE OF THE WEBSITE. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
            </p>
            
            <p>
              PLEASE READ THESE TERMS AND CONDITIONS ("T&C") CAREFULLY. BY ACCESSING, BROWSING, USING THE WEBSITE OR ANY OTHER WEBSITE, MOBILE VERSION OF THE WEBSITE OR MOBILE APPLICATION (THE TOGETHER "WEBSITE") OR AVAILING ANY OF THE PRODUCTS OF DHSS WELLNESS INDIA PVT LTD (HEREINAFTER REFERRED TO AS "COMPANY" OR "US" OR "WE") YOU INCLUDING THE PERSONS WHO BROWSES OR THE PERSONS WHO ORDERS THE PRODUCT AGREE TO BE BOUND BY ALL OF THE T&C MENTIONED HEREUNDER.
            </p>
            
            <p>
              Only persons who can enter into legally binding contract under the Indian Contract Act, 1872 can use the Website and/or transact on the Website. Any minor who wishes to use or access the Website is required to conduct such transaction through their legal guardian or parents. If you represent a company, partnership firm or sole proprietorship, you shall be eligible to access and use the Website to conduct the transactions on its behalf only if you have been duly authorized by way of necessary corporate action, as may be prescribed statutorily and/or under the charter documents of such entity.
            </p>
            
            <p>
              The Company reserves the right to amend or revise the T&C at any time by uploading a revised or amended T&C on the Website with or without prior notice. The amended T&C will be effective immediately after it is uploaded on this Website. Your access or use of the Website following any such changes constitutes your acceptance to follow and You shall be bound by these T&C, as amended. The version of the T&C that will apply to your order will be those uploaded on the Website at the time you use or access or place your order. For this reason, we encourage you to review these T&C each time you access and place your order. This T&C does not alter in any way the terms or conditions of any other written agreement you may have with the Company for other products or services. If you do not agree to this T&C (including any referenced policies or guidelines), please immediately terminate your use of the Website. If you would like to print this T&C, please press CTRL + P.
            </p>
            
            <p>
              You may only access the Website for lawful purposes. You are solely responsible for the knowledge of and adherence to any and all laws, rules, and regulations pertaining to your use of the Website.
            </p>
            
            <p>
              We reserve the right to block any user and permanently disable user account if we believe in our sole discretion that action of such user has resulted in breach of fair usage policy or T&C.
            </p>

            <section className="mt-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">PRODUCTS</h2>
              
              <div className="space-y-4">
                <div>
                  <h3 className="font-semibold text-gray-800 mb-2">Terms of Offer:</h3>
                  <p>
                    The Website offers for sale certain products ("Products"). The Products shall include trial products and the products offered free of cost. By placing an order for the Products through the Website, you agree to the terms and conditions set forth in this T&C. The Products described on the Website, and any samples thereof we may provide to you, are for personal use only. You may not sell or resell any of the Products, or samples thereof, you receive from us unless agreed otherwise. We reserve the right, with or without notice, to cancel or reduce the quantity of any Products to be provided to you that we believe, in our sole discretion, may result in the violation of our T&C.
                  </p>
                </div>
                
                <p>
                  The Company may change, suspend, or discontinue the availability of any of the Products at any time, without any notice or liability. You acknowledge that the price payable in connection with the Product or any service, may be subject to change, without notice or liability.
                </p>
                
                <p>
                  While describing our Products on our Website, we endeavour to be as accurate as possible. To the extent implied by applicable law, we do not warrant that the Product descriptions, colours, information or other content available on the Website are accurate, complete, reliable, current, or error-free. The Website may contain typographical errors or inaccuracies and may not be complete or updated. Such errors, inaccuracies or omissions may also relate to pricing and availability of the Product or services. Please note that the Product pictures are indicative and may not match the actual Product.
                </p>
                
                <div>
                  <h3 className="font-semibold text-gray-800 mb-2">Customer Solicitation:</h3>
                  <p className="mb-3">
                    By accessing the Website or placing an order or sending any information, you are communicating with the Company electronically and you agree to receive communications (including transactional, promotional and/or commercial messages) from the Company periodically and as and when required. We may communicate with you by e-mail, SMS, phone call or by posting notices on the Website or by any other mode of communication.
                  </p>
                  <p className="mb-2">
                    At any point of time, you have the right to withdraw your consent by following the below stated opt-out procedure.
                  </p>
                  <div>
                    <p className="font-semibold text-gray-800 mb-2">Opt Out Procedure:</p>
                    <p className="mb-2">We provide 3 easy ways to opt out of from future Customer Solicitations.</p>
                    <ul className="list-disc list-inside space-y-1 ml-4">
                      <li>You may use the opt out link found in any email solicitation that you may receive.</li>
                      <li>You may also choose to opt out, via sending your email by addressing to: karmaterra.social@gmail.com</li>
                      <li>You may send a written removal request to 1-Vaidehi Apartment, Off Veera Desai Road, Andheri West, Mumbai - 400058</li>
                    </ul>
        </div>
      </div>

                <div>
                  <h3 className="font-semibold text-gray-800 mb-2">Proprietary Rights:</h3>
                  <p>
                    All the brand names owned and licensed to the Company are exclusive property of the Company, its affiliates, partners or licensors, and is protected by laws of India, including laws governing all applicable forms of intellectual property. The Company has the proprietary rights and trade secrets in the Products. You shall not copy, reproduce, modify, duplicate, re-publish, re-sell or re-distribute any Product manufactured and/or distributed by the Company in whole or in part or in any other form whatsoever. The Company also has rights to all trademarks and trade dress and specific layouts of this webpage, including without limitation calls to action, text placement, images, technology, content, software and other materials, which appear on the Website, including its looks and feel. No trademark is granted in connection with the Products or the materials contained on the Website. The access to the Website does not authorize anyone to use any trademarks in any manner. The trademarks displayed on the Website whether registered or unregistered, are the intellectual property of the Company.
                  </p>
                </div>
                
                <div>
                  <h3 className="font-semibold text-gray-800 mb-2">Tax:</h3>
                  <p>
                    If you purchase any Products, you will be responsible for paying any applicable taxes in relation to such purchase.
                  </p>
                </div>
              </div>
        </section>

            <section className="mt-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">WEBSITE</h2>
              
              <div className="space-y-4">
                <div>
                  <h3 className="font-semibold text-gray-800 mb-2">Your Account:</h3>
                  <p>
                    You may create and hold one user account ("Account") only. You will be responsible for maintaining confidentiality of your account, password, and restricting access to your computer, and you hereby accept responsibility for all activities that occur under your Account. You acknowledge that the information you provide, in any manner whatsoever, are not confidential or proprietary and does not infringe any rights of a third party in whatsoever nature. Each Account is non-transferrable and may not be sold, traded, combined, or otherwise shared with any other person.
                  </p>
                </div>
                
                <div>
                  <h3 className="font-semibold text-gray-800 mb-2">Content; Intellectual Property; Third Party Links:</h3>
                  <p>
                    In addition to making the Products available, the Website also offers information and marketing materials. The Website also offers information, both directly and through indirect links to third-party websites about nutritional and dietary supplements. The Company does not always create such information and the content published on the Website; instead, the information and content are often gathered from other sources. The Company does not endorse any such information or content and the Company expressly disclaims any and all liability in connection with the same. The Company is not responsible or liable for the information or the content or any damage or loss that may result from your access to or reliance on such information or content.
                  </p>
                </div>
                
                <div>
                  <h3 className="font-semibold text-gray-800 mb-2">Use of Website:</h3>
                  <p>
                    The Company is not responsible for any damages resulting from use of the Website by anyone. You will not use the Website for any illegal purposes. You will (a) abide by all applicable local, state, national, and international laws and regulations in your use of the Website (including laws regarding intellectual property), (b) not interfere with or disrupt the use and enjoyment of the Website by other users, (c) not resell material on the Website, (d) not engage, directly or indirectly, in transmission of "spam", chain letters, junk mail or any other type of unsolicited communication, and (e) not defame, harass, abuse, or disrupt other users of the Website.
                  </p>
                </div>
              </div>
        </section>

            <section className="mt-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Payment Method</h2>
              <p className="mb-2">
                All payments for the Products available on the Website must be made online through the following methods:
              </p>
              <ul className="list-disc list-inside space-y-1 ml-4 mb-2">
                <li>Credit Cards, Debit Cards, Net Banking, Digital Wallets, UPI, QR Code payments, PayPal and reward points.</li>
          </ul>
              <p className="font-semibold text-gray-800">
                Please note: We do not accept cash on delivery. All orders must be paid for online at the time of purchase.
              </p>
            </section>

            <section className="mt-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Pricing and Availability</h2>
              <p>
                The Prices and availability of the Products, offers and services provided or offered on the Website are subject to change without prior notice and at the sole discretion of the Company. The prices displayed at the Website are inclusive of goods and sales tax ("GST"), but do not include a delivery charge. For all orders under INR 599 (Indian Rupees Five Hundred and Ninety-Nine only), delivery charge of INR 40 (Indian Rupees Forty only) shall be levied. All orders above INR 599 (Indian Rupees Five Hundred and Ninety-Nine only) shall be delivered without any delivery charges.
              </p>
            </section>

            <section className="mt-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Delivery</h2>
              <p>
                For order containing multiple Products, delivery may be made in multiple shipments. Delivery usually takes 5-7 business days from the date of order placement. Upon placement of the order, the estimated shipping and delivery timelines shall be available on order details page. The estimated delivery times are indicative, hence there may be some unforeseeable delays, which are beyond our control.
              </p>
            </section>

            <section className="mt-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Returns and Refunds</h2>
              <p className="font-semibold text-gray-800 mb-2">IMPORTANT:</p>
              <p>
                All sales are final. We do not offer returns or refunds for change of mind or incorrect purchases. However, if you receive a product that is faulty, damaged, or significantly not as described, please contact us within 7 days of delivery. We will assess the issue and, if verified, offer a replacement, return, or refund as appropriate.
              </p>
            </section>

            <section className="mt-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">DISCLAIMER OF WARRANTIES</h2>
              <p>
                Your use of the Website and/or Products are at your sole risk. The Website and the Products are offered on an "as is" and "as available" basis. The Company expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose and non-infringement with respect to the Products or Website content, or any reliance upon or use of the Website content or Products.
              </p>
        </section>

            <section className="mt-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">LIMITATION OF LIABILITY</h2>
              <p>
                The Company takes no liability or exclusive remedy, in law, in equity, or otherwise, with respect to the Website content and Products and/or for any breach of this T&C. The Company will not be liable for any direct, indirect, incidental, special or consequential damages or loss in connection with this T&C or the Products in any manner.
              </p>
        </section>

            <section className="mt-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">INDEMNIFICATION</h2>
              <p>
                You will release, indemnify, defend and hold harmless the Company, and any of its contractors, agents, employees, officers, directors, shareholders, affiliates and assigns from all liabilities, claims, damages, costs and expenses, including reasonable attorney's fees and expenses, of third parties relating to or arising out of: (a) this T&C or the breach of your warranties, representations and obligations under this T&C; (b) the Website content or your use of the Website content; (c) the Products or your use of the Products.
              </p>
        </section>

            <section className="mt-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">GENERAL</h2>
              
              <div className="space-y-4">
                <div>
                  <h3 className="font-semibold text-gray-800 mb-2">Governing Law and Jurisdiction:</h3>
                  <p>
                    This T&C shall be construed in accordance with the applicable laws of India and will be governed by the laws of the state of Maharashtra without regard to its conflict of law principles to the contrary. Neither you nor the Company will commence or prosecute any suit, proceeding or claim to enforce the provisions of this T&C, to recover damages for breach of or default of this T&C, or otherwise arising under or by reason of this T&C, other than in courts located in State of Maharashtra. By using this Website or ordering Products, you consent to the jurisdiction and venue of such courts in connection with any action, suit, proceeding or claim arising under or by reason of this T&C.
                  </p>
                </div>
                
                <div>
                  <h3 className="font-semibold text-gray-800 mb-2">Termination:</h3>
                  <p>
                    The Company reserves the right to terminate your access to the Website if it reasonably believes, in its sole discretion, that you have breached any of the terms of this T&C. Following termination, you will not be permitted to use the Website and the Company may, in its sole discretion and without advance notice to you, cancel any outstanding orders for Products.
                  </p>
                </div>
                
                <p className="font-semibold text-gray-800">
                  By using this Website or ordering Products from this Website, you agree to be bound by this T&C.
                </p>
              </div>
        </section>

            <section className="mt-8 border-t pt-6">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Contact Us</h2>
              <div className="space-y-2">
                <p className="font-semibold text-gray-800">Customer Service Desk:</p>
                <p>Email: <a href="mailto:karmaterra.social@gmail.com" className="text-blue-600 hover:underline">karmaterra.social@gmail.com</a></p>
                <p>Phone: <a href="tel:+918591171598" className="text-blue-600 hover:underline">+91 8591171598</a></p>
                <p>Contact Days: Monday-Friday (From 9:00 AM to 6:00 PM)</p>
              </div>
        </section>

            <section className="mt-8 border-t pt-6">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Grievance Officer</h2>
              <p className="mb-4">
                The name and contact details of the Grievance Officer to handle any complaints in relation to the sale of Products or use of this Website are provided below:
              </p>
              <div className="space-y-2">
                <p><span className="font-semibold">Name:</span> Manisha Shekhar Asthana</p>
                <p>Email: <a href="mailto:karmaterra.social@gmail.com" className="text-blue-600 hover:underline">karmaterra.social@gmail.com</a></p>
                <p>Phone: <a href="tel:+918591171598" className="text-blue-600 hover:underline">+91 8591171598</a></p>
                <p>Time: Monday-Friday (From 9:00 AM to 6:00 PM)</p>
                <p>
                  <span className="font-semibold">Address:</span><br />
                  1-Vaidehi Apartment,<br />
                  Off Veera Desai Road, Andheri West,<br />
                  Mumbai - 400058
                </p>
              </div>
        </section>

            <footer className="mt-8 pt-6 border-t text-center">
              <p className="text-sm text-gray-600">© 2025 DHSS WELLNESS INDIA PVT LTD. All Rights Reserved</p>
            </footer>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
